# Generated by Django 4.2.1 on 2023-05-06 00:23

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=product.models.product_image_upload_path),
        ),
    ]
