# Generated by Django 4.2.1 on 2023-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_invoice_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_code',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
