# Generated by Django 4.2.1 on 2023-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_invoice_customer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_item',
            old_name='product',
            new_name='code',
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_code',
            field=models.CharField(max_length=20),
        ),
    ]
