# Generated by Django 4.2.1 on 2023-05-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_product_invoice_item_code_invoice_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_item',
            old_name='code',
            new_name='product',
        ),
    ]
