# Generated by Django 4.2.1 on 2023-05-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_code_invoice_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
