# Generated by Django 4.2.1 on 2023-05-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(max_length=50)),
                ('birthdate', models.DateField(verbose_name='出生日期')),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('use_billing_address', models.BooleanField(default=False)),
                ('billing_address', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('card_expiration_date', models.CharField(blank=True, max_length=7)),
                ('card_cvv', models.CharField(blank=True, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
