# Generated by Django 4.1.7 on 2023-05-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customer_customer_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="company",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="notes",
        ),
    ]
