# Generated by Django 4.1.7 on 2023-06-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
