# Generated by Django 4.1.7 on 2023-04-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Blog_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_content', models.TextField()),
                ('blog_user', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('blog_created', models.DateTimeField(auto_now=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='blog.blog_category')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comment_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('comment', models.TextField()),
                ('website', models.CharField(max_length=50)),
                ('comment_created', models.DateTimeField(auto_now=True)),
                ('blog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_item', to='blog.blog_item')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
