# Generated by Django 4.1.7 on 2023-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_item_blog_hates_blog_item_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_item',
            name='blog_comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
