# Generated by Django 4.1.7 on 2023-04-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_item_blog_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_item',
            name='blog_comments_count',
        ),
        migrations.AlterField(
            model_name='blog_item',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_item', to='blog.blog_category'),
        ),
        migrations.AlterField(
            model_name='comment_item',
            name='blog_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.blog_item'),
        ),
    ]
