# Generated by Django 4.1.7 on 2023-05-16 02:17

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blog_category_id_alter_blog_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.blog_image_upload_path
            ),
        ),
    ]
