# Generated by Django 4.1.7 on 2023-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chef", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chef",
            name="chef_title",
            field=models.CharField(default="123", max_length=100),
        ),
    ]
