# Generated by Django 4.1.7 on 2023-05-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chef", "0003_alter_chef_chef_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chef",
            options={"ordering": ("id",)},
        ),
    ]
