# Generated by Django 4.1.7 on 2023-05-14 10:34

import chef.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chef", "0004_alter_chef_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chef",
            name="chef_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=chef.models.chef_image_upload_path
            ),
        ),
    ]
