# Generated by Django 4.1.7 on 2023-04-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'menucategory',
                'verbose_name_plural': 'menucategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=20)),
                ('menu_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('menu_created_user', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('menu_created', models.DateTimeField(auto_now=True)),
                ('menu_likes', models.IntegerField(default=0)),
                ('menu_hates', models.IntegerField(default=0)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menu_category')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comment_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('comment', models.TextField()),
                ('website', models.CharField(max_length=50)),
                ('comment_created', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_comments', to='menu.menu_item')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
