# Generated by Django 4.2.1 on 2023-05-05 08:59

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_category',
            options={'ordering': ('id',), 'verbose_name': 'menucategory', 'verbose_name_plural': 'menucategories'},
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='image',
            field=models.ImageField(upload_to=menu.models.menu_item_image_upload_path),
        ),
    ]
